### ISSUE TITLE
Add folding rules for Midje fact, facts, tabular, provided, background, against-background statements

### ISSUE THREAD

**Issue by oryband** [sogaiu/tree-sitter-clojure#16]
It is common to nest Midje facts in facts (unit tests of unit tests), but treesitter only folds the top-most level. What is the best practice to tell treesitter to do this? Also won't hurt to add this to the docs.

**Comment by sogaiu** [comment]
I'm not very familiar with the folding in nvim-treesitter.

I just tried the instructions here: https://github.com/nvim-treesitter/nvim-treesitter#folding and I am seeing what looks similar to what you reported.

IIUC, I think it's a combination of neovim and nvim-treesitter that's providing the folding functionality, currently via this query: https://github.com/nvim-treesitter/nvim-treesitter/blob/048317174c61eb56a01746265e5e5328ed4110a3/queries/clojure/folds.scm

May be it's worth asking about this in nvim-treesitter's Zulip community?

If it turns out the folding rules are generally applicable, it might make sense to have them added to `folds.scm`, but if they are specific (e.g. I'm not a Midje user) may be they can be configured via user-specific queries via the mechanism described here: https://github.com/nvim-treesitter/nvim-treesitter#adding-queries

**Comment by sogaiu** [comment]
I'm going to close this as I think the issue lies elsewhere, but if it turns out otherwise, it can be reopened.

**Comment by nimaai** [comment]
i am not sure if this is related but folding works only on the toplevel `defn` forms. i have this setting in neovim:

```
vim.wo[0][0].foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.wo[0][0].foldmethod = 'expr'
```
